<?php


namespace Jxm\Ehr\Model;


use Ramsey\Uuid\Uuid;

class BgGroup extends EhrBasicModel
{
    const State_Normal = 0;     //正常
    const State_Stop = 100;     //停运

    public $incrementing = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->id = Uuid::uuid4()->toString();
        });
    }
}
